name: visual
favicon: null
layout_spectrum: 0.74455
typography_spectrum: 0.5469
title: visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8f8f8f'
    - '#5f5f5f'
    - '#d5d5d5'
    - '#afafaf'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
