name: visual
favicon: null
layout_spectrum: 0.74455
typography_spectrum: 0.5469
title: visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fef4b6'
    - '#4e6376'
    - '#91908b'
    - '#debe98'
  brandStrength: 1
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 1
purpose: []
