name: visual
favicon: null
layout_spectrum: 0.98576
typography_spectrum: 0.7671389018651098
title: visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8f8f8f'
    - '#5f5f5f'
    - '#d5d5d5'
    - '#afafaf'
  brandStrength: 0.6975890886969864
  lightness: 0.6876997465733439
  saturation: 0.3934202054515481
  rhythmicContrast: 0.5041792674455792
purpose: []
